version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      timezone: Europe/Paris
    open-pull-requests-limit: 10
